### PR TITLE
join multiple tables into one when when printing list of objects.

### PR DESCRIPTION
**Pull request by kaos**
While we're at it. Had an itch to fix this rather ugly thing... :P

From this:

```
$ GDAPI_URL=http://192.168.99.100:8080/v1 gdapi list-task
| Type | Id  | Name | Value      |
----------------------------------
| task | 1t2 | name | agent.ping |

| Type | Id  | Name | Value                  |
----------------------------------------------
| task | 1t3 | name | cleanup.task.instances |

| Type | Id  | Name | Value                 |
---------------------------------------------
| task | 1t4 | name | config.item.migration |

| Type | Id  | Name | Value                           |
-------------------------------------------------------
| task | 1t5 | name | config.item.source.version.sync |

| Type | Id  | Name | Value            |
----------------------------------------
| task | 1t6 | name | config.item.sync |

| Type | Id  | Name | Value            |
----------------------------------------
| task | 1t7 | name | database.cleanup |

| Type | Id  | Name | Value          |
--------------------------------------
| task | 1t8 | name | process.replay |

| Type | Id  | Name | Value           |
---------------------------------------
| task | 1t1 | name | purge.resources |

| Type | Id  | Name | Value                   |
-----------------------------------------------
| task | 1t9 | name | resource.change.monitor |

| Type | Id   | Name | Value                   |
------------------------------------------------
| task | 1t10 | name | resource.change.publish |
```

To this:

```
$ GDAPI_URL=http://192.168.99.100:8080/v1 gdapi list-task
| Type | Id   | Name | Value                           |
--------------------------------------------------------
| task | 1t2  | name | agent.ping                      |
| task | 1t3  | name | cleanup.task.instances          |
| task | 1t4  | name | config.item.migration           |
| task | 1t5  | name | config.item.source.version.sync |
| task | 1t6  | name | config.item.sync                |
| task | 1t7  | name | database.cleanup                |
| task | 1t8  | name | process.replay                  |
| task | 1t1  | name | purge.resources                 |
| task | 1t9  | name | resource.change.monitor         |
| task | 1t10 | name | resource.change.publish         |
```

### CODE REVIEW

**Comment by kaos** [comment]
@ibuildthecloud bump 😜 

Know you have more important stuff to do, just thought it would be nice to get this in, eventually.. ;)

**Comment by ibuildthecloud** [comment]
@kaos I totally overlooked this repo for the last year.  I just merged a PR to support python 3 and would like to include this too.  Can you rebase?  I guess you changes need to be compatible with python 3 and 2

**Comment by kaos** [comment]
sure thing, will look into it, hopefully I'll remember it tomorrow. ;)

**Comment by kaos** [comment]
Not sure if it's my setup that's incomplete or something (haven't attempted to use python 3 before), but I get this on current master:

```
$ python3 gdapi.py -h
Traceback (most recent call last):
  File "gdapi.py", line 861, in <module>
    _main()
  File "gdapi.py", line 852, in _main
    client = _cli_client(sys.argv)
  File "gdapi.py", line 847, in _cli_client
    return _from_env(prefix, **dict_args)
  File "gdapi.py", line 632, in _from_env
    return factory(**result)
  File "gdapi.py", line 197, in __init__
    self._load_schemas()
  File "gdapi.py", line 312, in _load_schemas
    schema_text = self._get_cached_schema()
  File "gdapi.py", line 521, in _get_cached_schema
    cached_schema = self._get_cached_schema_file_name()
  File "gdapi.py", line 497, in _get_cached_schema_file_name
    h = self._get_schema_hash()
  File "gdapi.py", line 488, in _get_schema_hash
    h.update(self._url)
TypeError: Unicode-objects must be encoded before hashing
```

So, I'll make a best effort on making my changes python 3 compatible, but I'm not sure if it'll work (unless I manage to resolve the above).

**Comment by kaos** [comment]
Ok, that may be due to the cache file being saved with the py2.7 version.. adding a `--no-cache` option gets pass that, but now it fails on:

```
Traceback (most recent call last):
  File "gdapi.py", line 865, in <module>
    _main()
  File "gdapi.py", line 862, in _main
    _run_cli(client, args)
  File "gdapi.py", line 772, in _run_cli
    _print_cli(client, result)
  File "gdapi.py", line 551, in _print_cli
    print(obj._as_table())
  File "gdapi.py", line 105, in _as_table
    wrapfunc=lambda x: str(x))
  File "gdapi.py", line 584, in indent
    logicalRows = [rowWrapper(row) for row in rows]
  File "gdapi.py", line 584, in <listcomp>
    logicalRows = [rowWrapper(row) for row in rows]
  File "gdapi.py", line 582, in rowWrapper
    return [[substr or '' for substr in item] for item in map(None, *newRows)]  # NOQA
  File "gdapi.py", line 582, in <listcomp>
    return [[substr or '' for substr in item] for item in map(None, *newRows)]  # NOQA
TypeError: 'NoneType' object is not callable
```

**Comment by kaos** [comment]
rebased onto `master`, works ok for me on py2.7, but not on py3.5 (with the previous error, `'NoneType' object is not callable`), but I get that error on `master` as well, using py3.5..

**Comment by cjellick** [comment]
Very stale. Closing

**Pull request closed without merging**
